# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc1cf059978fea63b7f05875215c7c2e00b4d6b1aa4f22d2a58b5e544bb123367a2bec3fd7f3918c193460ba585e50f7135ecc6afdf247a05d946f197393351e

test:
  secret_key_base: e61d08c37377b8aeb58bd4725995c7a2c191a58454f977ff93708e40a8af2cfac8241ff04e232b51ec2a9d629f829090cf037c568f89cd2124e4652cf89e6e08

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
